class ValidationUserError(Exception): ...


class ValidationFirstNameError(Exception): ...


class ValidationSecondNameError(Exception): ...


class ValidationPhoneNumberError(Exception): ...


class ValidationEmailError(Exception): ...


class InputMessageError(Exception): ...


class InvalidSubKey(Exception): ...


class UserError(Exception): ...


class SubscriptionError(Exception): ...


class LessonError(Exception): ...


class ColumnCSVError(Exception): ...
