class ValidationUserError(BaseException): ...


class ValidationFirstNameError(BaseException): ...


class ValidationSecondNameError(BaseException): ...


class ValidationPhoneNumberError(BaseException): ...


class ValidationEmailError(BaseException): ...


class ErrorContextArgs(BaseException): ...


class InvalidSubKey(BaseException): ...


class UserError(BaseException): ...


class SubscriptionError(BaseException): ...


class LessonError(BaseException): ...


class ColumnCSVError(BaseException): ...
